In [1]:
import numpy as np
array =np.zeros( (2,3) )
print(array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [2]:
import numpy as np
array =np.ones( (1,5) )
print(array)

[[1. 1. 1. 1. 1.]]


In [4]:
n=int(input("Number of the inputs: "))
arr=[]
for i in range(0,n):
    elem=int(input("Enter the number: "))
    arr.append(elem)
avg=sum(arr)/n    
print("Average of the given numbers: ", round(avg,2))

Number of the inputs: 4
Enter the number: 110
Enter the number: 4
Enter the number: -20
Enter the number: 50
Average of the given numbers:  36.0
